"""empty message

Revision ID: 4bb236497713
Revises: a06c82e1a32a
Create Date: 2021-08-11 18:34:09.065980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb236497713'
down_revision = 'a06c82e1a32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buddy', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buddy', 'bio')
    # ### end Alembic commands ###
