"""empty message

Revision ID: b83615784002
Revises: 
Create Date: 2021-08-08 13:44:40.011301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83615784002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy',
    sa.Column('buddy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zipcode', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('morning', sa.Boolean(), nullable=True),
    sa.Column('afternoon', sa.Boolean(), nullable=True),
    sa.Column('evening', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('buddy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buddy')
    # ### end Alembic commands ###
